### ISSUE TITLE
GUI: Make Apply button in settings work properly

### ISSUE THREAD

**Issue by lohani2280** [NIT-dgp/UIP#259] opened 2016-12-17 19:57 UTC
gives permission error whenever changes made in settings  are applied by clicking on "Apply" button.

EDIT :-
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/UIP-0.0.3-py3.5.egg/uiplib/GUI.py", line 275, in handle_settings
    update_settings(self.new_settings)
  File "/usr/local/lib/python3.5/dist-packages/UIP-0.0.3-py3.5.egg/uiplib/utils/utils.py", line 18, in update_settings
    with open(temp_file, "w+") as _file:
PermissionError: [Errno 13] Permission denied: '/home/user1/.uip/temp.json'

**Comment by abhsag24** [comment] 2016-12-17 20:02
@lohani2280 can you post the traceback? @nemaniarjun can this be due to the same reason we had with folders?

**Comment by nemaniarjun** [comment] 2016-12-17 20:02
Does it work with `sudo`?

**Comment by nemaniarjun** [comment] 2016-12-17 20:03
Yeah I'll look into this

**Comment by abhsag24** [comment] 2016-12-17 20:04
@nemaniarjun maybe use `tempfile` ? a fix for this should be easy

**Comment by nemaniarjun** [comment] 2016-12-17 20:06
On it.

**Comment by nemaniarjun** [comment] 2016-12-17 20:46
@lohani2280 can you post details on how to reproduce the error? I am unable to reproduce it. (Everything works perfectly for me)

**Comment by lohani2280** [comment] 2016-12-17 21:01
@nemaniarjun  run UIP --ui -> go to settings -> fill in all the details and then -> click "Apply".

**Comment by nemaniarjun** [comment] 2016-12-17 21:07
@lohani2280 I don't get any error and it works for me perfectly. 
Make sure you have installed UIP using latest code.
If problem still persists, give me more details, like: OS you are using, etc

**Comment by lohani2280** [comment] 2016-12-17 21:15
I just updated my codebase (actually its already updated) . but the problem is still there . I am using Ubuntu 16.04 LTS

**Comment by abhsag24** [comment] 2016-12-22 13:31
@lohani2280 are u still facing the issue? did u try deleting your `.uip` folderand reinstalling again?

**Comment by lohani2280** [comment] 2017-01-05 12:41
@abhsag24 Its working completely fine now after deleting . so i am closing this .

**Closed** 2017-01-05 12:42 UTC
Labels: area/GUI, bug, difficulty/low
