### ISSUE TITLE
Option for different URL's other than reddit

### ISSUE THREAD

**Issue by abhsag24** [NIT-dgp/UIP#12] opened 2016-04-19 08:19 UTC
i think UIP should be able to extract images of a considerable resolution from any website

**Comment by nkprince007** [comment] 2016-11-19 21:25
I would recommend [this](unsplash.com) bro

**Comment by nkprince007** [comment] 2016-11-19 21:25
It provides an API too..

**Comment by Aniq55** [comment] 2016-11-20 11:22
I think [QuoteFancy](https://quotefancy.com) would be a great place to take pics from. But they also have a page in [Reddit](https://www.reddit.com/r/Quotefancy/)

**Comment by nemaniarjun** [comment] 2016-12-13 18:51
Duplicate of #162

**Closed** 2016-12-13 18:52 UTC
Labels: difficulty/hard, feature
